name: ipv6-test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
          os: [windows-2022]

    runs-on: ${{ matrix.os }}

    steps:
      - name: setup dig
        run: choco upgrade -y bind-toolsonly

      - name: dig A
        run: dig api.slido-staging.com A

      - name: dig AAAA
        run: dig api.slido-staging.com AAAA

      - name: ipv4
        run: curl -m 3 -4 --verbose https://api.slido-staging.com/api/latest/ping

      - name: ipv6
        run: curl -m 3 -6 --verbose https://api.slido-staging.com/api/latest/ping
