name: ipv6-test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
          os: [ubuntu-latest, windows-2022]

    runs-on: ${{ matrix.os }}

    steps:
      - name: setup warp
        if: runner.os == 'Linux'
        uses: fscarmen/warp-on-actions@v1.1
        with:
          stack: ipv6

      - name: ipconfig
        run: curl -m 9 -6 --verbose https://ifconfig.co

      - name: slido
        run: curl -m 9 -6 --verbose https://api.slido-staging.com/api/latest/ping
